### ISSUE TITLE
Can't build cowsay example

### ISSUE THREAD

**Issue by johannesloibl** [AmadeusITGroup/uvbox#7]
When trying to replicate your example with cowsay:
```toml
[package]
name = "cowsay"
script = "cowsay"
```

I'm getting following error:
<img width="1748" height="286" alt="Image" src="https://github.com/user-attachments/assets/f5923517-617c-41ff-a417-33f79837ff60" />

**Comment by Coruscant11** [comment]
@johannesloibl Hi! Could you check again with the 1.0.3?
Thanks!!

**Comment by johannesloibl** [comment]
> [@johannesloibl](https://github.com/johannesloibl) Oh, really?! What is your configuration so that I can reproduce? Because I validated on my side with a virtual machine and it works well. Are you using the latest version?

Using uvbox 1.0.3. 
Python 3.11.4
I'm on Windows 11 Enterprise - Version 10.0.22631 Build 22631
Configuration as described above.

Command: ``uvbox pypi --config .\uxbox.toml``

**Comment by Coruscant11** [comment]
@johannesloibl Ok now IT SHOULD be fixed! Can you please test with the 1.0.5? 😄 
Thanks for your patience.

**Comment by johannesloibl** [comment]
Sorry to disappoint you but the issue still exists with 1.0.5 on my side :D
I'd be happy to provide more information, but it seems there is no log files in the build directory.

**Comment by Coruscant11** [comment]
@johannesloibl at least, at every iteration I solve a real issue. 😄

Maybe tell me which terminal are you using? Windows Terminal with Powershell?

**Comment by johannesloibl** [comment]
Yes Powershell
